apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: suppliers-microservice-secret
  namespace: statex-apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: suppliers-microservice-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/prod/suppliers-microservice
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/prod/auth-microservice
        property: JWT_SECRET
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: secret/prod/suppliers-microservice
        property: PAYMENT_API_KEY
    - secretKey: PAYMENT_APPLICATION_ID
      remoteRef:
        key: secret/prod/suppliers-microservice
        property: PAYMENT_APPLICATION_ID
    - secretKey: PAYMENT_WEBHOOK_API_KEY
      remoteRef:
        key: secret/prod/suppliers-microservice
        property: PAYMENT_WEBHOOK_API_KEY

